### ISSUE TITLE
Instant "Failed to connect" when trying to configure the add-on

### ISSUE THREAD

**Issue by braham2019** [jimmyd-be/Home-Assistant-Sensor-Renson-Ventilation#6]
Hi,

I am already manually boosting the ventilation of my Renson Healthbox using a switch:

```
#
# Switches
#
# Renson
  - platform: rest
    name: boost_ventilatie_badkamer
    resource: "http://192.168.0.5/v1/api/boost/2"
    method: put
    body_on: '{"enable": true, "level": 200, "timeout": 3600}'
    body_off: '{"enable": false}'
    is_on_template: "{{ value_json.enable }}"
```

I saw that there is an integration, but whenever I try to configure it, i get the "Failed to connect" error when entering the IP address. Either "192.168.0.5" or "http://192.168.0.5". I don't see any errors showing up in the log. 

How can I debug this ?

Thanks

**Comment by jimmyd-be** [comment]
This integration only works with the Renson endura delta devices. You are trying to use the Renson heatbox with the integration this is not a Endura Delta device and therefore not working.
