### ISSUE TITLE
Current integration is not starting

### ISSUE THREAD

**Issue by esys4u** [jimmyd-be/Home-Assistant-Sensor-Renson-Ventilation#7]
Current integration is not starting  ( installed by HACS ) and sensor conf was added to configuration.yaml

HA 2023.1.7
HACS 1.30.0

Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/__init__.py:529
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 16:34:03 (1 occurrences)
Last logged: 16:34:03

[140117635755040] The system cannot restart because the configuration is not valid: Platform error sensor.renson_ventilation - Integration 'renson_ventilation' not found.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 529, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Platform error sensor.renson_ventilation - Integration 'renson_ventilation' not found.

**Comment by esys4u** [comment]
after change config file to

sensor:
  - platform: renson
    host: my_renson_devie_hostname
    
  
I'm getting:
ERROR (MainThread) [homeassistant.components.sensor] The renson platform for the sensor integration does not support platform setup. Please remove it from your config.

**Comment by jimmyd-be** [comment]
You can configure the integration using the UI. Can you try that?

**Comment by esys4u** [comment]
@jimmyd-be after installation by HACS  integration is not visible anywhere in HA

**Comment by jimmyd-be** [comment]
Did you restart Home Assistent after the installation of the integration?

**Comment by esys4u** [comment]
yes, not only HA but even OS, there no option to see this integration in HA, there is only information in log that HA detected not supported integration - only INFO or WARN without any additional information

**Comment by jimmyd-be** [comment]
Just checked on my installation and it is still showing. After the reboot did you installed the integration using the normal hands integration page? There should be Renson on the list. If you don't find that I will investigate further this weekend.

**Comment by dimitridelanghe** [comment]
i can confirm that this is working on this system : 
Home Assistant 2023.2.4 
Supervisor 2023.01.1
Operating System 8.5
Frontend 20230202.0 - latest 

HACS version : 1.31.0

Device info : endura delta by Renson
Firmware: 0.0.69
Hardware: 7 

Indeed @esys4u  u have to add the integration after u added it via HACS. (then u don't need to update your yaml files)

**Comment by jimmyd-be** [comment]
I don't got any repsonse back. I will close this one. If it is still not fixed please create another issue.

**Comment by esys4u** [comment]
Sorry I' was out few weeks, it's workin using HACS install sorry for problem.
